//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections;

namespace AssemblyCSharp
{
	public class Collectible : MonoBehaviour //, BoxCollider // multiple inheritance
    {


        public Collectible()
        {

        }

        void OnTriggerEnter (Collider other)
        {
            //gameObject.renderer.isVisible = false; // read only
            Recipe.foundCollectible(this);
        }
    }

   


}

