//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

public abstract class Inventory
{

    private static Dictionary<String,int> items;

    public static Dictionary<String, int> Items
    {
        get
        {
            return items;
        }
    }

    static Inventory()
    {
        items = new Dictionary<String,int >();

        items.Add("Starflower", 8);
		items.Add ("Mint", 2);
    }
}


