//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

public class Recipe
{
    
    private Dictionary<String, int> medicine;

    public String name;
    
    public Dictionary<String, int> Medicine
    {
        get
        {
            return medicine;
        }
    }

    private Dictionary<String, int> vaccination;
    
    public Dictionary<String, int> Vaccination
    {
        get
        {
            return vaccination;
        }
    }
    
    public Recipe(String name)
    {      
        this.name = name;
        medicine = new Dictionary<String, int>();
        medicine.Add("Annanas", 5 );
        medicine.Add("Bananen", 15);
        medicine.Add("Schnittlauch", 25);
        medicine.Add("Salamandablut", 2);

        vaccination = new Dictionary<String,int >();
        vaccination.Add("Baumrinde", 15);
        vaccination.Add("Sesam", 2);
    }
    
}


