//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

public abstract class Stats
{

    private static Dictionary<Recipe, int> diseases;

    public static Dictionary<Recipe, int> Dieseases
    {
        get
        {
            return diseases;
        }
    }

    static Stats()
    {
        diseases = new Dictionary<Recipe,int >();

        diseases.Add(new Recipe("Pest"), 5);
        
        diseases.Add(new Recipe("Keuchhusten"), 5);
        
        diseases.Add(new Recipe("Fieber"), 5);
        
        diseases.Add(new Recipe("Schnupfen"), 5);
    }
}


